services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pastetry
